### ISSUE TITLE
 Warning: Failed context type: The context `headroomInit` is marked as required in `HeadComponent`, but its value is `undefined`.

### ISSUE THREAD

**Issue by j-mendez** [Jekiwijaya/react-native-web-headroom#1]
I want to start off by saying thank you for your great work. Context should not be required at all for this.

**Comment by j-mendez** [comment]
Fixed on master. Is there any chance that you are going to drastically change this repo? Because this works flawlessly and super performant if so ima fork before its Lost haha.

**Comment by Jekiwijaya** [comment]
@jeffreymendez1993 thank you! this is my first package actually.

Maybe, I just found in react-native, it's actually have a lot communication between native and JS, and I haven't found the solution yet. If it can be reduced, it would be more smooth.

Glad someone like it 😀

**Comment by j-mendez** [comment]
@Jekiwijaya I noticed one draw back. The way its designed that controlls the paddingTop for the scroll container which works for the initial UI. But when you are actually trying to implement the pull to refresh. Its not that easy. 


Heres a example.

component={scrollContainer}

scrollContainer = 
       <ScrollView
        ref={input => { this.mainScroller = input; }}
        {...props}
        refreshControl={
          <RefreshControl
            refreshing={DataStore.refreshing}
            onRefresh={this._onRefresh}
            tintColor={!Base.android ? 'transparent': Colors.activeColor}
            colors={[Base.colors.white, Colors.activeColor, Base.colors.white]}
            progressBackgroundColor={Colors.activeColor}
          />
        }


And in my <HeadComponent a 50-55 px height navBar. 

Inside my ScrollComponent there is a top view that is only shown initially like Facebooks Status update.

        <View style={[{borderBottomWidth: Base.hairlineWidth, borderColor: Colors.borderGrey, elevation:1}]}>
          {this.renderTabs()}
          {this.switchListMode()}
        </View>
